### ISSUE TITLE
打包后所有资源加载失败。

### ISSUE THREAD

**Issue by JZLeung** [kuitos/import-html-entry#22]
![image](https://user-images.githubusercontent.com/7995232/73131557-26bd8900-4048-11ea-928b-4130b80924d2.png)

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#why-dynamic-imported-assets-missing

**Comment by JZLeung** [comment]
@kuitos 
默认已经使用了，但是没用，依旧加载失败。

![image](https://user-images.githubusercontent.com/7995232/73131874-88ccbd00-404d-11ea-970e-9b00302a9db1.png)


react16 的访问地址是 localhost:8888/react16

直接访问是可以正常打开，通过 localhost:8888/main 去加载则无法访问。

**Comment by kuitos** [comment]
参考example里的 vue 项目看下哪里的问题

**Comment by JZLeung** [comment]
> 参考example里的项目看下哪里的问题

example 中没有 build。这是我自己写的打包命令打包好的demo。

**Comment by kuitos** [comment]
example 里有 build https://github.com/umijs/qiankun/blob/master/examples/react16/package.json#L14

我跑了下 example，无法复现你的问题

**Comment by JZLeung** [comment]
打包后，entry 不需要修改？？？

![image](https://user-images.githubusercontent.com/7995232/73135487-a9147000-407d-11ea-970f-128acd9b0d0b.png)

**Comment by kuitos** [comment]
要改
