### ISSUE TITLE
getGlobalProp返回了parcelRequire而不是myvariable(parcel serve --global myvariable)

### ISSUE THREAD

**Issue by feibi** [kuitos/import-html-entry#6]
`parcel` 导出`umd`格式时，生成了全局属性`parcelRequire`，
 `src/utils` 的`getGlobalProp`方法遍历最后一个添加到`window`的属性，返回了`parcelRequire`。

重现步骤：
1. 主项目（umi）用 `@umijs/plugin-qiankun/master`
2. 子项目（parcel）是 `qiankun/exapmles/vue`
3. 启动所有服务
4. 子项目加载时报错`You need to export the functional lifecycles in vue app entry`

临时解决方式：
```js
//src/utils  getGlobalProp方法下面添加一行
if (!global.hasOwnProperty(p)) continue;
if(p==='parcelRequire')continue;
```

希望可以对这个情况做下兼容

> 上面只是本地调试临时解决方案。还没找到为什么`getGlobalProp`返回最后属性是`parcelRequire`, 而不是`myvariable`。qiankun的完整例子运行就没这个问题。

**Comment by kuitos** [comment]
parcel 不作为生产可用参考
