### ISSUE TITLE
加载资源的切面可以暴露出来么？

### ISSUE THREAD

**Issue by howel52** [kuitos/import-html-entry#7]
https://github.com/kuitos/import-html-entry/blob/110b0bfe33cfc7b77d469823b8816ee4a345438f/src/index.js#L13

目前获取资源走的是 window.fetch

**Comment by kuitos** [comment]
具体需求是?

**Comment by howel52** [comment]
以下观点结合乾坤来看(如果不适合放在这里可以挪一下)：

import-html-entry 通过使用 window.fetch 来获取子应用入口以及背后所依赖的资源，对于入口 entry 而言，我们这边的思路是起一个 render server 来做 html 的入口管理 （而不是 cdn 意义上的版本控制），那么对于这个入口就会涉及到鉴权，不同公司鉴权的方式不太一样，有些放 cookie 有些自定义 header，无法直接使用业务目前正在跑的封装后的类 fetch 方法； 

window.fetch 还会受到浏览器版本的影响；

**Comment by kuitos** [comment]
懂了，可以开放出去

**Comment by HadeAs** [comment]
> 以下观点结合乾坤来看(如果不适合放在这里可以挪一下)：
> 
> import-html-entry 通过使用 window.fetch 来获取子应用入口以及背后所依赖的资源，对于入口 entry 而言，我们这边的思路是起一个 render server 来做 html 的入口管理 （而不是 cdn 意义上的版本控制），那么对于这个入口就会涉及到鉴权，不同公司鉴权的方式不太一样，有些放 cookie 有些自定义 header，想直接使用业务目前正在跑的封装后的类 fetch 方法；
> 
> window.fetch 还会受到浏览器版本的影响；

是的，目前我自己改造了一下，代码如下：
```
require('es6-promise').polyfill();
require('isomorphic-fetch');
import processTpl, { genLinkReplaceSymbol } from './process-tpl';
import { getGlobalProp, getInlineCode, noteGlobalProps } from './utils';

const styleCache = {};
const scriptCache = {};
const embedHTMLCache = {};
// const fetch = window.fetch.bind(window);
```
这样可以在IE中跑起来

**Comment by kuitos** [comment]
polyfill 在外层加就好了，不用改这个库 @HadeAs

**Comment by kuitos** [comment]
@howel52 直接来个 pr ？
