### ISSUE TITLE
SCRIPT_SRC_REGEX 正则问题

### ISSUE THREAD

**Issue by benben77** [kuitos/import-html-entry#8]
你好：

在代码中使用了正则`SCRIPT_SRC_REGEX`：其值为：`/.*\ssrc=('|")(\S+)\1.*/`，用以匹配类似`src="..."`形式的src属性

但是标签属性是可以省略引号的，例如webpack打包时html插件通常会去掉属性的引号来压缩代码

因此建议修改匹配属性的正则，例如类似vue中的：

```
var attribute = /^\s*([^\s"'<>\/=]+)(?:\s*(=)\s*(?:"([^"]*)"+|'([^']*)'+|([^\s"'=<>`]+)))?/;
```

**Comment by kuitos** [comment]
pr is welcome:smile:
